name: booking_system_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 5.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common
  cupertino_icons: ^1.0.5
  nb_utils: ^4.6.10
  google_fonts: ^3.0.1
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.2

  # Firebase
  firebase_crashlytics: ^2.8.2
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  firebase_storage: ^10.2.18
  firebase_remote_config: ^2.0.9
  cloud_firestore: ^3.1.18
  paginate_firestore: ^1.0.3+1
  flutter_html: ^3.0.0-alpha.5

  # Push Notification
  onesignal_flutter: ^3.3.2

  # State Management
  mobx: ^2.0.7+3
  flutter_mobx: ^2.0.6+1

  # Icon
  flutter_vector_icons: ^1.0.0
  flutter_svg: ^1.1.0

  # Image
  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  file_picker: ^4.5.1
  lottie: ^1.3.0

  # Other
  date_time_picker: 2.1.0
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.3
  flutter_custom_tabs: ^1.0.4
  permission_handler: ^10.0.0

  # Social Login
  google_sign_in: ^5.3.3

  # Payment Gateways
  razorpay_flutter: ^1.3.0
  flutterwave_standard: 1.0.3
  flutter_stripe: ^3.1.0

  # Map
  google_maps_flutter: ^2.1.8
  geolocator: ^8.2.1
  geocoding: ^2.0.4

  flutter_staggered_animations: 1.0.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  modal_bottom_sheet: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/lottie/

